## IMDB Movie Analysis With PowerBI

In [1]:
# import packages
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn
import numpy as np

In [2]:
df=pd.read_csv(r"C:\Users\LENOVO\Downloads\IMDB_Movies.csv")
df.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [3]:
df

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [4]:
df.shape

(5043, 28)

In [5]:
df.dtypes

color                         object
director_name                 object
num_critic_for_reviews       float64
duration                     float64
director_facebook_likes      float64
actor_3_facebook_likes       float64
actor_2_name                  object
actor_1_facebook_likes       float64
gross                        float64
genres                        object
actor_1_name                  object
movie_title                   object
num_voted_users                int64
cast_total_facebook_likes      int64
actor_3_name                  object
facenumber_in_poster         float64
plot_keywords                 object
movie_imdb_link               object
num_user_for_reviews          object
language                      object
country                       object
content_rating                object
budget                       float64
title_year                   float64
actor_2_facebook_likes       float64
imdb_score                   float64
aspect_ratio                 float64
movie_facebook_likes           int64
dtype: object

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      5024 non-null   object
 1   director_name              4939 non-null   object
 2   num_critic_for_reviews     4993 non-null   float64
 3   duration                   5028 non-null   float64
 4   director_facebook_likes    4939 non-null   float64
 5   actor_3_facebook_likes     5020 non-null   float64
 6   actor_2_name               5030 non-null   object
 7   actor_1_facebook_likes     5036 non-null   float64
 8   gross                      4159 non-null   float64
 9   genres                     5043 non-null   object
 10  actor_1_name               5036 non-null   object
 11  movie_title                5043 non-null   object
 12  num_voted_users            5043 non-null   int64
 13  cast_total_facebook_likes  5043 non-null   int64
 14  actor_3_name               5020 non-null   object
 15  facenumber_in_poster       5030 non-null   float64
 16  plot_keywords              4890 non-null   object
 17  movie_imdb_link            5043 non-null   object
 18  num_user_for_reviews       5023 non-null   object
 19  language                   5029 non-null   object
 20  country                    5038 non-null   object
 21  content_rating             4740 non-null   object
 22  budget                     4551 non-null   float64
 23  title_year                 4935 non-null   float64
 24  actor_2_facebook_likes     5030 non-null   float64
 25  imdb_score                 5043 non-null   float64
 26  aspect_ratio               4714 non-null   float64
 27  movie_facebook_likes       5043 non-null   int64
dtypes: float64(12), int64(3), object(13)
memory usage: 1.1+ MB

In [7]:
df.isnull().sum()

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          20
language                      14
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [8]:
df[['num_critic_for_reviews','director_facebook_likes',
    'actor_3_facebook_likes','actor_1_facebook_likes',
    'num_voted_users','cast_total_facebook_likes',
    'facenumber_in_poster','num_user_for_reviews',
    'actor_2_facebook_likes','movie_facebook_likes']] = df[['num_critic_for_reviews','director_facebook_likes',
                                                            'actor_3_facebook_likes','actor_1_facebook_likes',
                                                            'num_voted_users','cast_total_facebook_likes',
                                                            'facenumber_in_poster','num_user_for_reviews',
                                                            'actor_2_facebook_likes','movie_facebook_likes']].fillna(0)
df.isnull().sum()

color                         19
director_name                104
num_critic_for_reviews         0
duration                      15
director_facebook_likes        0
actor_3_facebook_likes         0
actor_2_name                  13
actor_1_facebook_likes         0
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster           0
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews           0
language                      14
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes         0
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [9]:
df.shape

(5043, 28)

In [10]:
df.isnull().sum()

color                         19
director_name                104
num_critic_for_reviews         0
duration                      15
director_facebook_likes        0
actor_3_facebook_likes         0
actor_2_name                  13
actor_1_facebook_likes         0
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster           0
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews           0
language                      14
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes         0
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [15]:
df['num_critic_for_reviews'] = df['num_critic_for_reviews'].astype(int)
df['duration'] = df['duration'].astype(int)
df['director_facebook_likes'] = df['director_facebook_likes'].astype(int)
df['actor_3_facebook_likes'] = df['actor_3_facebook_likes'].astype(int)
df['actor_1_facebook_likes'] = df['actor_1_facebook_likes'].astype(int)
df['facenumber_in_poster'] = df['facenumber_in_poster'].astype(int)
df['num_user_for_reviews'] = df['num_user_for_reviews'].astype(int)
df['title_year'] = df['title_year'].astype(int)
df['actor_2_facebook_likes'] = df['actor_2_facebook_likes'].astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [16]:
df.dtypes

color                         object
director_name                 object
num_critic_for_reviews         int32
duration                     float64
director_facebook_likes      float64
actor_3_facebook_likes       float64
actor_2_name                  object
actor_1_facebook_likes       float64
gross                        float64
genres                        object
actor_1_name                  object
movie_title                   object
num_voted_users                int64
cast_total_facebook_likes      int64
actor_3_name                  object
facenumber_in_poster         float64
plot_keywords                 object
movie_imdb_link               object
num_user_for_reviews          object
language                      object
country                       object
content_rating                object
budget                       float64
title_year                   float64
actor_2_facebook_likes       float64
imdb_score                   float64
aspect_ratio                 float64
movie_facebook_likes           int64
dtype: object

In [17]:
df = df[['movie_imdb_link','color','movie_title','language','title_year','duration',
        'director_name','actor_1_name','actor_2_name','actor_3_name',
        'genres','country','budget','gross','plot_keywords','content_rating',
        'aspect_ratio','imdb_score','num_critic_for_reviews','num_user_for_reviews',
        'num_voted_users','director_facebook_likes','actor_1_facebook_likes',
        'actor_2_facebook_likes','actor_3_facebook_likes','cast_total_facebook_likes',
        'movie_facebook_likes','facenumber_in_poster']]
df.tail()

,movie_imdb_link,color,movie_title,language,title_year,duration,director_name,actor_1_name,actor_2_name,actor_3_name,...,num_critic_for_reviews,num_user_for_reviews,num_voted_users,director_facebook_likes,actor_1_facebook_likes,actor_2_facebook_likes,actor_3_facebook_likes,cast_total_facebook_likes,movie_facebook_likes,facenumber_in_poster
5038,http://www.imdb.com/title/tt3000844/?ref_=fn_t...,Color,Signed Sealed Delivered,English,2013.0,87.0,Scott Smith,Eric Mabius,Daphne Zuniga,Crystal Lowe,...,1,6,629,2.0,637.0,470.0,318.0,2283,84,2.0
5039,http://www.imdb.com/title/tt2071645/?ref_=fn_t...,Color,The Following,English,NaN,43.0,NaN,Natalie Zea,Valorie Curry,Sam Underwood,...,43,359,73839,0.0,841.0,593.0,319.0,1753,32000,1.0
5040,http://www.imdb.com/title/tt2107644/?ref_=fn_t...,Color,A Plague So Pleasant,English,2013.0,76.0,Benjamin Roberds,Eva Boehnke,Maxwell Moody,David Chandler,...,13,3,38,0.0,0.0,0.0,0.0,0,16,0.0
5041,http://www.imdb.com/title/tt2070597/?ref_=fn_t...,Color,Shanghai Calling,English,2012.0,100.0,Daniel Hsia,Alan Ruck,Daniel Henney,Eliza Coupe,...,14,9,1255,0.0,946.0,719.0,489.0,2386,660,5.0
5042,http://www.imdb.com/title/tt0378407/?ref_=fn_t...,Color,My Date with Drew,English,2004.0,90.0,Jon Gunn,John August,Brian Herzlinger,Jon Gunn,...,43,84,4285,16.0,86.0,23.0,16.0,163,456,0.0

In [18]:
df = df.drop_duplicates('movie_imdb_link').reset_index(drop=True)

In [19]:
df.tail()

,movie_imdb_link,color,movie_title,language,title_year,duration,director_name,actor_1_name,actor_2_name,actor_3_name,...,num_critic_for_reviews,num_user_for_reviews,num_voted_users,director_facebook_likes,actor_1_facebook_likes,actor_2_facebook_likes,actor_3_facebook_likes,cast_total_facebook_likes,movie_facebook_likes,facenumber_in_poster
4914,http://www.imdb.com/title/tt3000844/?ref_=fn_t...,Color,Signed Sealed Delivered,English,2013.0,87.0,Scott Smith,Eric Mabius,Daphne Zuniga,Crystal Lowe,...,1,6,629,2.0,637.0,470.0,318.0,2283,84,2.0
4915,http://www.imdb.com/title/tt2071645/?ref_=fn_t...,Color,The Following,English,NaN,43.0,NaN,Natalie Zea,Valorie Curry,Sam Underwood,...,43,359,73839,0.0,841.0,593.0,319.0,1753,32000,1.0
4916,http://www.imdb.com/title/tt2107644/?ref_=fn_t...,Color,A Plague So Pleasant,English,2013.0,76.0,Benjamin Roberds,Eva Boehnke,Maxwell Moody,David Chandler,...,13,3,38,0.0,0.0,0.0,0.0,0,16,0.0
4917,http://www.imdb.com/title/tt2070597/?ref_=fn_t...,Color,Shanghai Calling,English,2012.0,100.0,Daniel Hsia,Alan Ruck,Daniel Henney,Eliza Coupe,...,14,9,1255,0.0,946.0,719.0,489.0,2386,660,5.0
4918,http://www.imdb.com/title/tt0378407/?ref_=fn_t...,Color,My Date with Drew,English,2004.0,90.0,Jon Gunn,John August,Brian Herzlinger,Jon Gunn,...,43,84,4285,16.0,86.0,23.0,16.0,163,456,0.0

In [20]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
title_year,4813.0,2.002445e+03,1.245346e+01,1916.00,1999.00,2005.00,2011.00,2.016000e+03
duration,4904.0,1.070891e+02,2.527858e+01,7.00,93.00,103.00,118.00,5.110000e+02
budget,4434.0,3.928822e+07,2.085579e+08,218.00,6000000.00,19850000.00,43000000.00,1.221550e+10
gross,4056.0,4.762156e+07,6.736387e+07,162.00,5008728.50,25035665.00,61099406.25,7.605058e+08
aspect_ratio,4593.0,2.222105e+00,1.402514e+00,1.18,1.85,2.35,2.35,1.600000e+01
imdb_score,4919.0,6.437874e+00,1.127606e+00,1.60,5.80,6.60,7.20,9.500000e+00
num_critic_for_reviews,4919.0,1.366355e+02,1.204358e+02,0.00,47.00,107.00,191.00,8.130000e+02
num_voted_users,4919.0,8.261820e+04,1.382858e+05,5.00,8356.50,33158.00,93757.50,1.689764e+06
director_facebook_likes,4919.0,6.763830e+02,2.804312e+03,0.00,6.00,44.00,188.00,2.300000e+04
actor_1_facebook_likes,4919.0,6.481639e+03,1.509431e+04,0.00,606.00,981.00,11000.00,6.400000e+05
actor_2_facebook_likes,4919.0,1.616787e+03,4.005784e+03,0.00,275.00,592.00,912.00,1.370000e+05
actor_3_facebook_likes,4919.0,6.280112e+02,1.622195e+03,0.00,129.00,362.00,631.00,2.300000e+04
cast_total_facebook_likes,4919.0,9.574646e+03,1.815999e+04,0.00,1394.00,3044.00,13611.50,6.567300e+05
movie_facebook_likes,4919.0,7.345294e+03,1.920071e+04,0.00,0.00,160.00,2000.00,3.490000e+05
facenumber_in_poster,4919.0,1.372840e+00,2.022053e+00,0.00,0.00,1.00,2.00,4.300000e+01

In [21]:
df

,movie_imdb_link,color,movie_title,language,title_year,duration,director_name,actor_1_name,actor_2_name,actor_3_name,...,num_critic_for_reviews,num_user_for_reviews,num_voted_users,director_facebook_likes,actor_1_facebook_likes,actor_2_facebook_likes,actor_3_facebook_likes,cast_total_facebook_likes,movie_facebook_likes,facenumber_in_poster
0,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,Color,Avatar,English,2009.0,178.0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,...,723,3054,886204,0.0,1000.0,936.0,855.0,4834,33000,0.0
1,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,Color,Pirates of the Caribbean: At World's End,English,2007.0,169.0,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,...,302,1238,471220,563.0,40000.0,5000.0,1000.0,48350,0,0.0
2,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,Color,Spectre,English,2015.0,148.0,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,...,602,994,275868,0.0,11000.0,393.0,161.0,11700,85000,1.0
3,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,Color,The Dark Knight Rises,English,2012.0,164.0,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,...,813,2701,1144337,22000.0,27000.0,23000.0,23000.0,106759,164000,0.0
4,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,NaN,Star Wars: Episode VII - The Force AwakensÂ ...,NaN,NaN,NaN,Doug Walker,Doug Walker,Rob Walker,NaN,...,0,,8,131.0,131.0,12.0,0.0,143,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4914,http://www.imdb.com/title/tt3000844/?ref_=fn_t...,Color,Signed Sealed Delivered,English,2013.0,87.0,Scott Smith,Eric Mabius,Daphne Zuniga,Crystal Lowe,...,1,6,629,2.0,637.0,470.0,318.0,2283,84,2.0
4915,http://www.imdb.com/title/tt2071645/?ref_=fn_t...,Color,The Following,English,NaN,43.0,NaN,Natalie Zea,Valorie Curry,Sam Underwood,...,43,359,73839,0.0,841.0,593.0,319.0,1753,32000,1.0
4916,http://www.imdb.com/title/tt2107644/?ref_=fn_t...,Color,A Plague So Pleasant,English,2013.0,76.0,Benjamin Roberds,Eva Boehnke,Maxwell Moody,David Chandler,...,13,3,38,0.0,0.0,0.0,0.0,0,16,0.0
4917,http://www.imdb.com/title/tt2070597/?ref_=fn_t...,Color,Shanghai Calling,English,2012.0,100.0,Daniel Hsia,Alan Ruck,Daniel Henney,Eliza Coupe,...,14,9,1255,0.0,946.0,719.0,489.0,2386,660,5.0
4918,http://www.imdb.com/title/tt0378407/?ref_=fn_t...,Color,My Date with Drew,English,2004.0,90.0,Jon Gunn,John August,Brian Herzlinger,Jon Gunn,...,43,84,4285,16.0,86.0,23.0,16.0,163,456,0.0

In [22]:
df.to_csv('IMDB_Movies_final.csv', index=False)

In [23]:
df

,movie_imdb_link,color,movie_title,language,title_year,duration,director_name,actor_1_name,actor_2_name,actor_3_name,...,num_critic_for_reviews,num_user_for_reviews,num_voted_users,director_facebook_likes,actor_1_facebook_likes,actor_2_facebook_likes,actor_3_facebook_likes,cast_total_facebook_likes,movie_facebook_likes,facenumber_in_poster
0,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,Color,Avatar,English,2009.0,178.0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,...,723,3054,886204,0.0,1000.0,936.0,855.0,4834,33000,0.0
1,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,Color,Pirates of the Caribbean: At World's End,English,2007.0,169.0,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,...,302,1238,471220,563.0,40000.0,5000.0,1000.0,48350,0,0.0
2,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,Color,Spectre,English,2015.0,148.0,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,...,602,994,275868,0.0,11000.0,393.0,161.0,11700,85000,1.0
3,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,Color,The Dark Knight Rises,English,2012.0,164.0,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,...,813,2701,1144337,22000.0,27000.0,23000.0,23000.0,106759,164000,0.0
4,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,NaN,Star Wars: Episode VII - The Force AwakensÂ ...,NaN,NaN,NaN,Doug Walker,Doug Walker,Rob Walker,NaN,...,0,,8,131.0,131.0,12.0,0.0,143,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4914,http://www.imdb.com/title/tt3000844/?ref_=fn_t...,Color,Signed Sealed Delivered,English,2013.0,87.0,Scott Smith,Eric Mabius,Daphne Zuniga,Crystal Lowe,...,1,6,629,2.0,637.0,470.0,318.0,2283,84,2.0
4915,http://www.imdb.com/title/tt2071645/?ref_=fn_t...,Color,The Following,English,NaN,43.0,NaN,Natalie Zea,Valorie Curry,Sam Underwood,...,43,359,73839,0.0,841.0,593.0,319.0,1753,32000,1.0
4916,http://www.imdb.com/title/tt2107644/?ref_=fn_t...,Color,A Plague So Pleasant,English,2013.0,76.0,Benjamin Roberds,Eva Boehnke,Maxwell Moody,David Chandler,...,13,3,38,0.0,0.0,0.0,0.0,0,16,0.0
4917,http://www.imdb.com/title/tt2070597/?ref_=fn_t...,Color,Shanghai Calling,English,2012.0,100.0,Daniel Hsia,Alan Ruck,Daniel Henney,Eliza Coupe,...,14,9,1255,0.0,946.0,719.0,489.0,2386,660,5.0
4918,http://www.imdb.com/title/tt0378407/?ref_=fn_t...,Color,My Date with Drew,English,2004.0,90.0,Jon Gunn,John August,Brian Herzlinger,Jon Gunn,...,43,84,4285,16.0,86.0,23.0,16.0,163,456,0.0

In [24]:
df.to_csv('C:/Users/LENOVO/Downloads/IMDB_Movies_final.csv')

In [25]:
df

,movie_imdb_link,color,movie_title,language,title_year,duration,director_name,actor_1_name,actor_2_name,actor_3_name,...,num_critic_for_reviews,num_user_for_reviews,num_voted_users,director_facebook_likes,actor_1_facebook_likes,actor_2_facebook_likes,actor_3_facebook_likes,cast_total_facebook_likes,movie_facebook_likes,facenumber_in_poster
0,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,Color,Avatar,English,2009.0,178.0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,...,723,3054,886204,0.0,1000.0,936.0,855.0,4834,33000,0.0
1,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,Color,Pirates of the Caribbean: At World's End,English,2007.0,169.0,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,...,302,1238,471220,563.0,40000.0,5000.0,1000.0,48350,0,0.0
2,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,Color,Spectre,English,2015.0,148.0,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,...,602,994,275868,0.0,11000.0,393.0,161.0,11700,85000,1.0
3,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,Color,The Dark Knight Rises,English,2012.0,164.0,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,...,813,2701,1144337,22000.0,27000.0,23000.0,23000.0,106759,164000,0.0
4,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,NaN,Star Wars: Episode VII - The Force AwakensÂ ...,NaN,NaN,NaN,Doug Walker,Doug Walker,Rob Walker,NaN,...,0,,8,131.0,131.0,12.0,0.0,143,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4914,http://www.imdb.com/title/tt3000844/?ref_=fn_t...,Color,Signed Sealed Delivered,English,2013.0,87.0,Scott Smith,Eric Mabius,Daphne Zuniga,Crystal Lowe,...,1,6,629,2.0,637.0,470.0,318.0,2283,84,2.0
4915,http://www.imdb.com/title/tt2071645/?ref_=fn_t...,Color,The Following,English,NaN,43.0,NaN,Natalie Zea,Valorie Curry,Sam Underwood,...,43,359,73839,0.0,841.0,593.0,319.0,1753,32000,1.0
4916,http://www.imdb.com/title/tt2107644/?ref_=fn_t...,Color,A Plague So Pleasant,English,2013.0,76.0,Benjamin Roberds,Eva Boehnke,Maxwell Moody,David Chandler,...,13,3,38,0.0,0.0,0.0,0.0,0,16,0.0
4917,http://www.imdb.com/title/tt2070597/?ref_=fn_t...,Color,Shanghai Calling,English,2012.0,100.0,Daniel Hsia,Alan Ruck,Daniel Henney,Eliza Coupe,...,14,9,1255,0.0,946.0,719.0,489.0,2386,660,5.0
4918,http://www.imdb.com/title/tt0378407/?ref_=fn_t...,Color,My Date with Drew,English,2004.0,90.0,Jon Gunn,John August,Brian Herzlinger,Jon Gunn,...,43,84,4285,16.0,86.0,23.0,16.0,163,456,0.0